manifest = "cf0b5b9e498fb9b29c12a5c9d59884875f3461b99de6fce2aa7077c05002ca72"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-static_assert"
target = "//:static_assert"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.34.1" ]
revision = "78678e93a067c0cb555f7cef8471b85865298420"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.34.1" ]
revision = "a9fe7b7aee5ad5b824372ff9f0c2589687ed5879"

[lock."github.com/buckaroo-pm/boost-static_assert"]
versions = [ "1.34.1" ]
revision = "12ac232daab5e01e1a57b1ca27f7625051602ba6"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.34.1" ]
revision = "e6e9e4c92f837811c99559042d8a901bff8feea5"
