manifest = "d464bfc53bc6f2c80295bfe003d533fa52f7142b89b2066e63b9e0f9cc095520"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-static_assert"
target = "//:static_assert"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.29.0" ]
revision = "82a04d57db7fa1da396d6f59d4b93734a6a081b2"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.29.0" ]
revision = "8c2507b89c28a5d46cd3908027e1bc76be09e436"

[lock."github.com/buckaroo-pm/boost-static_assert"]
versions = [ "1.29.0" ]
revision = "abcab2a742d5ecf83b2c7efab6908f0febdd0710"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.29.0" ]
revision = "3483dd9a6f942b9ce7d7786b3ce714fea181e6e8"
