manifest = "278049e2047483d23ed9723ce16187c6e6b49c9e36894f2cc0dd15788fdf1565"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-static_assert"
target = "//:static_assert"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.51.0" ]
revision = "171d2ac727246bcb7ac5d0b7d008c74a724ed445"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.51.0" ]
revision = "784e15d77cd9f02ee2da75a27e46b50a4343e385"

[lock."github.com/buckaroo-pm/boost-static_assert"]
versions = [ "1.51.0" ]
revision = "ca853bd8456f027d7fc9daa87e616fb7619d94dd"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.51.0" ]
revision = "fc1e6879f4ba327e8fa5671647648683c1f2138c"
