manifest = "1ecf48b092ae90e57b2dfc49d3bbaf2625777591910a9162cf8c38347628e1bf"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-static_assert"
target = "//:static_assert"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.46.1" ]
revision = "72805600b44f7e4b63be95f755d9bd3f6507a031"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.46.1" ]
revision = "a216a8a0d4ca8e9a0106992dac0d491de7831dcd"

[lock."github.com/buckaroo-pm/boost-static_assert"]
versions = [ "1.46.1" ]
revision = "dda6fcaf4a79f8eebd3ad253c73f5b684e413d7d"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.46.1" ]
revision = "53791bee68fb0891b2e0b0755373281e40e981e7"
