manifest = "5ab21251305d8418863e425cb6d249e3fea3149df7e4b97d870940957182cc00"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-static_assert"
target = "//:static_assert"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.35.0" ]
revision = "a71e4983666230295b605f9ec2f0d00b5166498d"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.35.0" ]
revision = "693fb62875f39d0ff647596c2a585dce0b80cc17"

[lock."github.com/buckaroo-pm/boost-static_assert"]
versions = [ "1.35.0" ]
revision = "0e70c106c9c4dc55bb453228ea88e1b6fb282768"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.35.0" ]
revision = "5ea4e0555566bb1e59ce5a544fc3a66ca1404281"
