manifest = "59605dceb3e082c5db879a5ed46b902858f116f1b8a495ea38d186ae897e1f49"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-static_assert"
target = "//:static_assert"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.27.0" ]
revision = "5ff80475a056e8194c2fb40f6da10f36b91bd480"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.27.0" ]
revision = "55fab12e16f7099039878ca679cbc226a7a27d77"

[lock."github.com/buckaroo-pm/boost-static_assert"]
versions = [ "1.27.0" ]
revision = "4ef24f92ad860e3cd7be1e725e5992414aabc9e5"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.27.0" ]
revision = "ad7b5a33270638bfd056d8ca26425ee426e08472"
